const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor?.('#070b08'); tg.setBackgroundColor?.('#060906'); }
const state={page:'home',balance:1000,gamesPlayed:0,wins:0,angle:0};
const app=document.getElementById('app'),balance=document.getElementById('balance'),toast=document.getElementById('toast');
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.max(0,Math.floor(n)));
function setBalance(){balance.textContent=money(state.balance)}
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function render(){setBalance();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));if(state.page==='home')home();if(state.page==='games')games();if(state.page==='tasks')tasks();if(state.page==='profile')profile()}
function head(title,sub){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div></div>`}
function home(){app.innerHTML=`${head('Главное меню','Твоя коллекция энергетиков')}<section class="hero"><div class="eyebrow">ENERGY COLLECTION</div><h2>Собирай. <span class="lime">Улучшай.</span></h2><p>Заполняй полку энергетиками, выполняй задания и испытывай удачу в Upgrader.</p></section><div class="section-title"><span>Моя полка</span><em>0 / 9</em></div><section class="shelf-frame"><div class="shelf-top"></div><div class="shelf-grid">${Array.from({length:9},(_,i)=>`<div class="slot"><small>№ ${i+1}</small><div class="plus">+</div></div>`).join('')}</div></section><div class="section-title"><span>Игры</span></div><section class="card game-card"><div class="game-left"><div class="game-icon">↑</div><div><h3>Upgrader</h3><p>Попробуй улучшить свой энергетик.</p></div></div><button class="primary" id="homeUpgrade">Играть</button></section>`;document.getElementById('homeUpgrade').onclick=()=>{state.page='games';render();setTimeout(openUpgrader,50)}}
function games(){app.innerHTML=`${head('Игры','Испытай удачу')}<section class="card game-card"><div class="game-left"><div class="game-icon">↑</div><div><h3>Upgrader</h3><p>Улучши предмет, попав в зелёную зону.</p></div></div><button class="primary" id="openUpgrade">Открыть</button></section><div id="upgradeMount"></div>`;document.getElementById('openUpgrade').onclick=openUpgrader}
function openUpgrader(){const m=document.getElementById('upgradeMount');if(!m)return;m.innerHTML=`<section class="card upgrader"><div class="upgrade-head"><b>UPGRADER</b><div class="chance" id="chanceLabel">35%</div></div><div class="wheel-wrap"><div class="wheel" id="wheel" style="--success-angle:126deg"><div class="wheel-inner"><div class="arrows"><span>⌃</span><span>⌃</span></div></div></div><div class="pointer"></div></div><div class="upgrade-items"><div class="item"><div class="can">🥤</div><b>Energy Basic</b><small>×1.0</small></div><div class="arrow">➜</div><div class="item"><div class="can">⚡</div><b>Energy Pro</b><small>×2.0</small></div></div><div class="controls"><div class="amount"><span>Шанс</span><input id="chance" type="range" min="10" max="70" value="35"><b id="chanceValue">35%</b></div><button class="primary" id="upgradeBtn">⚡ Апгрейд · 50</button><button class="primary" id="maxBtn">MAX</button></div><div class="result" id="result">Готов к апгрейду</div></section>`;const c=document.getElementById('chance'),cv=document.getElementById('chanceValue'),cl=document.getElementById('chanceLabel');c.oninput=()=>{cv.textContent=c.value+'%';cl.textContent=c.value+'%'};document.getElementById('maxBtn').onclick=()=>{c.value=70;c.oninput()};document.getElementById('upgradeBtn').onclick=doUpgrade;m.scrollIntoView({behavior:'smooth',block:'start'})}
function doUpgrade(){const btn=document.getElementById('upgradeBtn'),wheel=document.getElementById('wheel'),result=document.getElementById('result'),chance=Number(document.getElementById('chance').value);if(state.balance<50){result.textContent='Недостаточно энергии';result.className='result danger';notify('Нужно 50 энергии');return}state.balance-=50;state.gamesPlayed++;setBalance();btn.disabled=true;btn.textContent='Крутим...';result.className='result muted';result.textContent='Определяем результат...';const success=Math.random()*100<chance,successAngle=chance*3.6;wheel.style.setProperty('--success-angle',`${successAngle}deg`);const target=success?(Math.random()*Math.max(4,successAngle-8)+4):(successAngle+32+Math.random()*Math.max(5,328-successAngle));state.angle+=1080+(360-target);wheel.style.transform=`rotate(${state.angle}deg)`;setTimeout(()=>{btn.disabled=false;btn.textContent='⚡ Апгрейд · 50';if(success){state.wins++;result.className='result';result.textContent='↑ УСПЕХ! Предмет улучшен';notify('Апгрейд успешен!')}else{result.className='result danger';result.textContent='✕ НЕУДАЧА — попробуй ещё раз';notify('Апгрейд не удался')}},3050)}
function tasks(){app.innerHTML=`${head('Задания','Выполняй и получай энергию')}<section class="tasks"><div class="card task"><div><strong>Открыть Upgrader</strong><small>Награда: ⚡ 100</small></div><button class="primary" onclick="notify('Задание выполнено')">Забрать</button></div><div class="card task"><div><strong>Сделать 3 апгрейда</strong><small>Награда: ⚡ 250</small></div><button class="primary" onclick="notify('Сыграй 3 раза')">Проверить</button></div><div class="card task"><div><strong>Посетить профиль</strong><small>Награда: ⚡ 50</small></div><button class="primary" onclick="notify('Задание выполнено')">Забрать</button></div></section>`}
function profile(){const wr=state.gamesPlayed?Math.round(state.wins/state.gamesPlayed*100):0;app.innerHTML=`${head('Профиль','Твоя статистика')}<section class="card profile-head"><div class="avatar">⚡</div><div><div class="eyebrow">ИГРОК</div><h2 style="margin:0;font-size:20px">Energy Hunter</h2><small class="muted">Telegram Mini App</small></div></section><div class="stat-grid"><div class="stat"><b>⚡ ${money(state.balance)}</b><span>Энергия</span></div><div class="stat"><b>${state.gamesPlayed}</b><span>Апгрейдов</span></div><div class="stat"><b>${state.wins}</b><span>Успешных</span></div><div class="stat"><b>${wr}%</b><span>Винрейт</span></div></div>`}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.page;render()}));render();
