const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor?.('#070b08'); tg.setBackgroundColor?.('#060906'); }
const state={page:'home',balance:0,gamesPlayed:0,wins:0,angle:0,provider:'cryptobot'};
const app=document.getElementById('app'),balance=document.getElementById('balance'),toast=document.getElementById('toast');
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.max(0,Math.floor(n)));
function setBalance(){balance.textContent=money(state.balance)}
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function render(){setBalance();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));if(state.page==='home')home();if(state.page==='games')games();if(state.page==='tasks')tasks();if(state.page==='profile')profile()}
function head(title,sub){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div></div>`}
function home(){app.innerHTML=`${head('Главное меню','Твоя коллекция энергетиков')}<section class="hero"><div class="eyebrow">ENERGY COLLECTION</div><h2>Собирай. <span class="lime">Улучшай.</span></h2><p>Собирай энергетики и выставляй их на свою дизайнерскую полку.</p></section><div class="section-title"><span>Моя полка</span><em>0 / 9</em></div><section class="display-shelf"><div class="shelf-level">${[1,2,3].map(i=>`<div class="shelf-empty"><span>пусто</span></div>`).join('')}</div><div class="shelf-level">${[4,5,6].map(i=>`<div class="shelf-empty"><span>пусто</span></div>`).join('')}</div><div class="shelf-level">${[7,8,9].map(i=>`<div class="shelf-empty"><span>пусто</span></div>`).join('')}</div><div class="shelf-feet"></div></section>`}
function games(){app.innerHTML=`${head('Игры','Испытай удачу')}<section class="card game-card"><div class="game-left"><div class="game-icon">↑</div><div><h3>Upgrader</h3><p>Улучши предмет, попав в зелёную зону.</p></div></div><button class="primary" id="openUpgrade">Открыть</button></section><div id="upgradeMount"></div>`;document.getElementById('openUpgrade').onclick=openUpgrader}
function openUpgrader(){const m=document.getElementById('upgradeMount');if(!m)return;m.innerHTML=`<section class="card upgrader"><div class="upgrade-head"><b>UPGRADER</b><div class="chance" id="chanceLabel">70%</div></div><div class="wheel-wrap"><div class="wheel" id="wheel" style="--success-angle:252deg"><div class="wheel-inner"><div class="arrows"><span>⌃</span><span>⌃</span></div></div></div><div class="pointer"></div></div><div class="upgrade-items"><div class="item"><div class="can">🥤</div><b>Energy Basic</b><small>×1.0</small></div><div class="arrow">➜</div><div class="item empty-result" id="targetItem"><div class="can">▱</div><b>Результат</b><small>пусто</small></div></div><div class="controls"><div class="amount"><span>Шанс</span><input id="chance" type="range" min="10" max="90" value="70"><b id="chanceValue">70%</b></div><button class="primary" id="upgradeBtn">⚡ Апгрейд · 50</button><button class="primary" id="maxBtn">MAX</button></div><div class="result" id="result">Готов к апгрейду</div></section>`;const c=document.getElementById('chance'),cv=document.getElementById('chanceValue'),cl=document.getElementById('chanceLabel');c.oninput=()=>{cv.textContent=c.value+'%';cl.textContent=c.value+'%'};document.getElementById('maxBtn').onclick=()=>{c.value=90;c.oninput()};document.getElementById('upgradeBtn').onclick=doUpgrade;m.scrollIntoView({behavior:'smooth',block:'start'})}
function doUpgrade(){const btn=document.getElementById('upgradeBtn'),wheel=document.getElementById('wheel'),result=document.getElementById('result'),target=document.getElementById('targetItem'),chance=Number(document.getElementById('chance').value);if(state.balance<50){result.textContent='Недостаточно энергии';result.className='result danger';notify('Нужно 50 энергии');return}state.balance-=50;state.gamesPlayed++;setBalance();btn.disabled=true;btn.textContent='Крутим...';result.className='result muted';result.textContent='Определяем результат...';const success=Math.random()*100<chance;const successAngle=chance*3.6;wheel.style.setProperty('--success-angle',`${successAngle}deg`);const targetAngle=success?(Math.random()*Math.max(4,successAngle-8)+4):(successAngle+Math.random()*Math.max(5,360-successAngle));state.angle+=1080+(360-targetAngle);wheel.style.transform=`rotate(${state.angle}deg)`;setTimeout(()=>{btn.disabled=false;btn.textContent='⚡ Апгрейд · 50';if(success){state.wins++;target.className='item';target.innerHTML='<div class="can">⚡</div><b>Energy Pro</b><small>×2.0</small>';result.className='result';result.textContent='↑ УСПЕХ! Предмет улучшен';notify('Апгрейд успешен!')}else{target.className='item empty-result';target.innerHTML='<div class="can">▱</div><b>Результат</b><small>пусто</small>';result.className='result danger';result.textContent='✕ НЕУДАЧА — выпало пустое поле';notify('Неудача — предмет потерян')}},3050)}
function walletModal(mode){document.querySelector('.modal')?.remove();const title=mode==='deposit'?'Пополнить баланс':'Вывести средства';const isDep=mode==='deposit';document.body.insertAdjacentHTML('beforeend',`<div class="modal show" id="walletModal"><div class="modal-card"><div class="modal-title"><h3>${title}</h3><button class="close" id="closeModal">×</button></div><div class="provider-row"><button class="provider ${state.provider==='cryptobot'?'active':''}" data-provider="cryptobot">CryptoBot</button><button class="provider ${state.provider==='xrocket'?'active':''}" data-provider="xrocket">xRocket</button></div><div class="field"><label>Сумма USDT</label><input id="walletAmount" type="number" min="1" step="0.01" placeholder="10"></div>${!isDep?'<div class="field"><label>Адрес кошелька / реквизит</label><input id="walletAddress" placeholder="Введите адрес"></div>':''}<div class="wallet-note">${isDep?'После подключения API здесь будет открываться счёт выбранного провайдера.':'Выводы должны подтверждаться сервером, чтобы ключи API не попадали в браузер.'}</div><div class="modal-actions"><button class="wallet-btn" id="cancelWallet">Отмена</button><button class="primary" id="submitWallet">${isDep?'Создать счёт':'Создать заявку'}</button></div></div></div>`);document.querySelectorAll('.provider').forEach(b=>b.onclick=()=>{state.provider=b.dataset.provider;document.querySelectorAll('.provider').forEach(x=>x.classList.toggle('active',x.dataset.provider===state.provider))});document.getElementById('closeModal').onclick=closeWallet;document.getElementById('cancelWallet').onclick=closeWallet;document.getElementById('submitWallet').onclick=()=>{const amount=Number(document.getElementById('walletAmount').value);if(!amount||amount<=0){notify('Укажи сумму');return}notify(`${isDep?'Счёт':'Заявка'} ${state.provider==='cryptobot'?'CryptoBot':'xRocket'} подготовлен`);closeWallet()}}
function closeWallet(){document.querySelector('.modal')?.remove()}
function tasks(){app.innerHTML=`${head('Задания','Выполняй и получай энергию')}<section class="tasks"><div class="card task"><div><strong>Открыть Upgrader</strong><small>Награда: ⚡ 100</small></div><button class="primary" onclick="notify('Скоро')">Забрать</button></div><div class="card task"><div><strong>Сделать 3 апгрейда</strong><small>Награда: ⚡ 250</small></div><button class="primary" onclick="notify('Сыграй 3 раза')">Проверить</button></div></section>`}
function profile(){const wr=state.gamesPlayed?Math.round(state.wins/state.gamesPlayed*100):0;app.innerHTML=`${head('Профиль','Баланс и статистика')}<section class="card profile-head"><div class="avatar">⚡</div><div><div class="eyebrow">ИГРОК</div><h2 style="margin:0;font-size:20px">Energy Hunter</h2><small class="muted">Telegram Mini App</small></div></section><section class="card wallet-card"><div class="section-title" style="margin:0"><span>Кошелёк</span><em>USDT</em></div><div class="wallet-actions"><button class="wallet-btn" id="depositBtn">＋ Пополнить</button><button class="wallet-btn" id="withdrawBtn">↗ Вывести</button></div><div class="provider-row"><button class="provider active" data-provider-view="cryptobot">CryptoBot</button><button class="provider" data-provider-view="xrocket">xRocket</button></div><div class="wallet-note">CryptoBot поддерживает invoices и payouts через Crypto Pay API; xRocket предоставляет Pay API для счетов и выводов. Реальное подключение требует серверной части и API-ключей.</div></section><div class="stat-grid"><div class="stat"><b>⚡ ${money(state.balance)}</b><span>Игровая энергия</span></div><div class="stat"><b>${state.gamesPlayed}</b><span>Апгрейдов</span></div><div class="stat"><b>${state.wins}</b><span>Успешных</span></div><div class="stat"><b>${wr}%</b><span>Винрейт</span></div></div>`;document.getElementById('depositBtn').onclick=()=>walletModal('deposit');document.getElementById('withdrawBtn').onclick=()=>walletModal('withdraw');document.querySelectorAll('[data-provider-view]').forEach(b=>b.onclick=()=>{state.provider=b.dataset.providerView;document.querySelectorAll('[data-provider-view]').forEach(x=>x.classList.toggle('active',x.dataset.providerView===state.provider));notify(state.provider==='cryptobot'?'Выбран CryptoBot':'Выбран xRocket')})}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.page;render()}));render();
